version: "3"
services:
  predictor:
    image: hub.graviti.cn/prediction-challenge:predictor-b7c3afb-20200921
    container_name: predictor
    command: ["python", "main.py", "-s", "192.168.10.74", "-p", "50051"]
    tty: true
    privileged: true
    volumes: 
      - /tmp:/Log
