version: "3"
services:
  simulator:
    image: hub.graviti.cn/prediction-challenge/simulator:20200925-4bd4d71
    container_name: simulator
    command: ["/prediction-challenge/simulator", "-p", "50051", "-c", "/prediction-challenge/conf/config.txt", "-l", "/mnt/simulator_logs"]
    tty: true
    privileged: true
    ports:
      - "50051:50051"
    volumes: 
      - /tmp:/mnt
    environment:
      - SCENARIO_ID=01
      - SCENARIO_NAME=default

